# Generated by Django 5.1.4 on 2026-02-09 13:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wardrobe', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TryOnResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('person_image_s3', models.CharField(max_length=500)),
                ('result_image_s3', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('processing_time_ms', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('garment_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tryon_results', to='wardrobe.wardrobeitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tryon_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tryon_results',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user'], name='tryon_resul_user_id_c37aad_idx'), models.Index(condition=models.Q(('status__in', ['pending', 'processing'])), fields=['status'], name='idx_tryon_active_status')],
            },
        ),
    ]
