# Generated by Django 5.1.4 on 2026-02-09 13:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wardrobe', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Outfit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('occasion', models.CharField(blank=True, choices=[('casual', 'Casual'), ('formal', 'Formal'), ('sport', 'Sport'), ('date', 'Date'), ('work', 'Work')], max_length=50)),
                ('season', models.CharField(blank=True, max_length=20)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('ai_recommended', 'AI Recommended'), ('daily', 'Daily Suggestion')], default='manual', max_length=20)),
                ('compatibility_score', models.FloatField(blank=True, null=True)),
                ('is_favorite', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outfits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'outfits',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DailyRecommendation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recommendation_date', models.DateField()),
                ('rank', models.IntegerField(default=1)),
                ('reason', models.TextField(blank=True)),
                ('was_accepted', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_recommendations', to=settings.AUTH_USER_MODEL)),
                ('outfit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='outfits.outfit')),
            ],
            options={
                'db_table': 'daily_recommendations',
                'ordering': ['rank'],
            },
        ),
        migrations.CreateModel(
            name='OutfitItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slot', models.CharField(choices=[('top', 'Top'), ('bottom', 'Bottom'), ('dress', 'Dress'), ('shoes', 'Shoes'), ('outerwear', 'Outerwear'), ('accessory', 'Accessory')], max_length=30)),
                ('outfit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='outfits.outfit')),
                ('wardrobe_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outfit_appearances', to='wardrobe.wardrobeitem')),
            ],
            options={
                'db_table': 'outfit_items',
            },
        ),
        migrations.AddIndex(
            model_name='outfit',
            index=models.Index(fields=['user'], name='outfits_user_id_4bf0b9_idx'),
        ),
        migrations.AddIndex(
            model_name='outfit',
            index=models.Index(fields=['user', 'source'], name='outfits_user_id_56b159_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyrecommendation',
            index=models.Index(fields=['user', 'recommendation_date'], name='daily_recom_user_id_37cef5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dailyrecommendation',
            unique_together={('user', 'recommendation_date', 'rank')},
        ),
        migrations.AddIndex(
            model_name='outfititem',
            index=models.Index(fields=['outfit'], name='outfit_item_outfit__71d8b1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='outfititem',
            unique_together={('outfit', 'slot')},
        ),
    ]
