# Generated by Django 5.1.4 on 2026-02-28 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outfits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outfit',
            name='occasion',
            field=models.CharField(blank=True, choices=[('casual', 'Casual'), ('formal', 'Formal'), ('business', 'Business'), ('sport', 'Sport'), ('party', 'Party'), ('date', 'Date'), ('work', 'Work')], max_length=50),
        ),
    ]
