# Generated by Django 5.1.4 on 2026-02-09 13:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WardrobeItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('top', 'Top'), ('bottom', 'Bottom'), ('dress', 'Dress'), ('outerwear', 'Outerwear'), ('shoes', 'Shoes'), ('accessory', 'Accessory')], max_length=50)),
                ('subcategory', models.CharField(blank=True, max_length=80)),
                ('primary_color', models.CharField(blank=True, max_length=30)),
                ('secondary_color', models.CharField(blank=True, max_length=30)),
                ('color_hex', models.CharField(blank=True, max_length=7)),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('season', models.CharField(choices=[('spring', 'Spring'), ('summer', 'Summer'), ('fall', 'Fall'), ('winter', 'Winter'), ('all', 'All Seasons')], default='all', max_length=20)),
                ('clip_embedding', models.JSONField(blank=True, null=True)),
                ('detection_data', models.JSONField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wardrobe_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'wardrobe_items',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WardrobeItemImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('s3_key', models.CharField(max_length=500)),
                ('image_type', models.CharField(choices=[('original', 'Original'), ('cropped', 'Cropped'), ('thumbnail', 'Thumbnail')], default='original', max_length=20)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('file_size_bytes', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('wardrobe_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='wardrobe.wardrobeitem')),
            ],
            options={
                'db_table': 'wardrobe_item_images',
            },
        ),
        migrations.AddIndex(
            model_name='wardrobeitem',
            index=models.Index(fields=['user', 'is_active'], name='wardrobe_it_user_id_7bf9f3_idx'),
        ),
        migrations.AddIndex(
            model_name='wardrobeitem',
            index=models.Index(fields=['user', 'category'], name='wardrobe_it_user_id_064bee_idx'),
        ),
        migrations.AddIndex(
            model_name='wardrobeitemimage',
            index=models.Index(fields=['wardrobe_item'], name='wardrobe_it_wardrob_c8a58b_idx'),
        ),
    ]
